// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtQ0kercIC2rNO1z1I6UapZr3O269A2iw',
    appId: '1:1035547798973:web:ecbf2b365d179ac08836d4',
    messagingSenderId: '1035547798973',
    projectId: 'loyalty-app-ab6b0',
    authDomain: 'loyalty-app-ab6b0.firebaseapp.com',
    storageBucket: 'loyalty-app-ab6b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr8qCg8kPdnGEWlPNfFNfFRc6Wp-riBPQ',
    appId: '1:1035547798973:android:3066c3ae87a0c7598836d4',
    messagingSenderId: '1035547798973',
    projectId: 'loyalty-app-ab6b0',
    storageBucket: 'loyalty-app-ab6b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl2fcoBHKlkHnOI5t7VRMedO8AC36PZlo',
    appId: '1:1035547798973:ios:deae8c7c17300e0b8836d4',
    messagingSenderId: '1035547798973',
    projectId: 'loyalty-app-ab6b0',
    storageBucket: 'loyalty-app-ab6b0.appspot.com',
    iosBundleId: 'com.example.loyaltyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl2fcoBHKlkHnOI5t7VRMedO8AC36PZlo',
    appId: '1:1035547798973:ios:0f33c0e77741ceb68836d4',
    messagingSenderId: '1035547798973',
    projectId: 'loyalty-app-ab6b0',
    storageBucket: 'loyalty-app-ab6b0.appspot.com',
    iosBundleId: 'com.example.loyaltyApp.RunnerTests',
  );
}
